### ISSUE TITLE
An alternative for Microsoft Translator?

### ISSUE THREAD

**Issue by ritzdevp** [microsoft/GLUECoS#4]
For the transliteration of Roman to Devnagari, it would be convenient to add support for more transliteration services.

**Comment by Genius1237** [comment]
Since the number of queries made to the API fall within the free tier of Microsoft Translator, we felt that users wouldn't have any issue using it.

If you would like to use a different service, I can point you to the part of the code where the changes have to be made for it.

https://github.com/microsoft/GLUECoS/blob/19fb6713ad2d22d181647db4aa2bd2c76aea4270/transliterator.py#L21-L53

In the method `get_transliteration`, `vocab` is a list of words that are to be transliterated. All you would have to do is to send the words in the `vocab`  to the other service. The method returns the variable `trans` which is a dictionary mapping each word in `vocab` to it's translation.

**Comment by ritzdevp** [comment]
Thanks a lot for the quick response. 
For future use, one can use `indic-transliteration` that provides Roman to Devnagar transliteration with a simple call `transliterate(vocab[j], sanscript.ITRANS, sanscript.DEVANAGARI)` .
